Blazing Pizza Store - ASP.NET core app
infracloudio/asp-dotnet-core-acorn pull request #1
Opened 2023-10-30 05:43 UTC by aashimodi14

2023-10-30 14:00 UTC, samkulkarni20 requested changes

2023-10-30 14:00 UTC, samkulkarni20 commented on Acornfile
1. Add the Acorn metadata, name, description, readme & icon
2. Doesn't it need any other containers/services?

2023-10-30 14:24 UTC, aashimodi14 commented on Acornfile
had missed to push the local changes, updated the acornfile
its included in the app itself

2023-10-31 06:50 UTC, samkulkarni20 approved these changes

2023-10-31 06:50 UTC, merged